// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDXr188gf7cha5-aLk7okWeqAax0uuoic',
    appId: '1:565854774950:web:380843326d19ddecf93667',
    messagingSenderId: '565854774950',
    projectId: 'progmob-14ff1',
    authDomain: 'progmob-14ff1.firebaseapp.com',
    storageBucket: 'progmob-14ff1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGXfol6l_9B5fP84fC5hWNxBRsK0VibW4',
    appId: '1:565854774950:android:3aa702cc91a5a004f93667',
    messagingSenderId: '565854774950',
    projectId: 'progmob-14ff1',
    storageBucket: 'progmob-14ff1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVKedlwyXTcWQOI03PD7OALugxbRtFqnE',
    appId: '1:565854774950:ios:cbe61263ef56589ef93667',
    messagingSenderId: '565854774950',
    projectId: 'progmob-14ff1',
    storageBucket: 'progmob-14ff1.appspot.com',
    iosClientId: '565854774950-fb2aiashhqrnsftug3e2u25ltj2f3t2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.modul2',
  );
}
